# pull the Python Docker image
FROM python

# Install PDM
RUN pip install pdm
RUN pip install uvicorn
RUN pip install fastapi
RUN pip install requests
RUN pip install httpx
RUN pip install asyncio

# Create the directory inside the container for the app
WORKDIR /usr/src/app

# our app is running on port 5000 within the container, so need to expose it
EXPOSE 5000

# the command that starts our app
CMD pdm install; pdm run start_server
